version: "3.8"

services:
  app:
    container_name: erpro-app
    build:
      context: .
      dockerfile: Dockerfile-app
    environment:
      - TZ=Asia/Seoul
    ports:
      - 9999:8080
    depends_on:
      - database #아래 서비스명 db가 먼저 생성이 돼야해서

  database:
    container_name: erpro-db
    build:
      context: .
      dockerfile: Dockerfile-db
    hostname: docker-mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: erpro
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: 1111